version: "3.7"

services: 
  app:
    container_name: front-app
    build: 
      context: .
      dockerfile: ${DOCKERFILE}
    ports:
    - ${PORT_EXPOSED}:${PORT}
    volumes: 
        - .:/app
        - ./node_modules:/app/node_modules
    environment: 
        - CHOKIDAR_USEPOLLING=true
        - NODE_ENV=${NODE_ENV}
    restart: unless-stopped